dist: xenial
language: bash
services: docker
matrix:
  include:
    - name: Setup with docker - docker-compose
      script:
        - docker-compose run web python3 manage.py flake
        - docker-compose run web python3 manage.py test
        - docker-compose run web python3 manage.py cov
    # We need to use Fedora container,
    # to test the use case "Setup without docker" on Fedora.
    - name: Setup without docker - pipenv
      install:
        - docker build --rm -t fedora-packages -f Dockerfile-without-docker .
      script:
        - |
          docker run --rm -t fedora-packages bash -cx "
            command -v python3 \
              && command -v pipenv \
              && pipenv --support \
              && pipenv install --dev \
              && pipenv run python3 manage.py flake \
              && pipenv run python3 manage.py test \
              && pipenv run python3 manage.py cov \
          "
  allow_failures:
  fast_finish: true
branches:
  only:
    - master
    # Enable "pull/*" branches to run Travis CI on forked repository.
    - /^pull\//
