dist: xenial
language: bash
services: docker
matrix:
  include:
    # Run multi arch cases on only cron mode at first, as it takes 30+ minutes.
    - name: Setup with docker
      script:
        - docker-compose run web python3 manage.py flake
        - docker-compose run web python3 manage.py test
        - docker-compose run web python3 manage.py cov
    - name: Setup without docker
      language: python
      python: "3.7"
      install:
        - pip3 install pipenv
        - pipenv install --dev
      script:
        - pipenv run python3 manage.py flake
        - pipenv run python3 manage.py test
        - pipenv run python3 manage.py cov
  allow_failures:
  fast_finish: true
branches:
  only:
    - master
    # Enable "pull/*" branches to run Travis CI on forked repository.
    - /^pull\//
