version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/packages
    image: packages:latest
    ports:
      - "80:80"
    volumes:
      - $PWD/..:/usr/share/fedoracommunity:z
      - $PWD/../fedoracommunity:/usr/lib/python2.7/site-packages/fedoracommunity:z
    command: ["/root/entry-point.sh"]
